title: Nothing But Waffles
description: A place to share my tinkering.
author: 
  name: Otto
  email: email here

remote_theme: jekyll/minima

minima:
  skin: solarized-dark
  social_links:
    - { platform: github,  user_url: "https://github.com/ottowishish" }

header_pages:
  - index.md
  - about.md

exclude:
  - README.md