title: Nothing But Waffles
description: A place to share my tinkering.
author: 
  name: Otto
  email: email here

remote_theme: jekyll/minima

minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/ottowishish" }

show_excerpts: true

header_pages:
  - _pages/index.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude:
  - README.md
  - .gitignore